#!/usr/bin/env python3

"""
Nom : BAKKALI Yahya
Matricule : 000445166
"""
from sys import argv
f = open(argv[1])

# Indices :
M, N = 0, 0
# Constantes :
L, l_i = 0, []

# Lire l'instance et extraire les données.
it = 0
for line in f:
    value = line.strip().split()
    if it == 0:
        M = int(value[1])
        L = value[0]
        it += 1
    else:
        N += int(value[1])
        for i in range(int(value[1])):
            l_i.append((value[0]))

f.close()

# Fonction objective :
objective = "\tobj: " + " + ".join("m_{}".format(i) for i in range(1, M + 1)) + "\n"

# Contraintes :
constraints = ""
# Contrainte 1 :
for j in range(1, M + 1):
    constraints += "\tc_1_{}: {} m_{} - ".format(j, L, j) + " - ".join("{} x_{}_{}({})".format(l_i[i - 1], i, j, l_i[i - 1]) for i in range(1, N + 1))
    constraints += " >= 0\n".format(L, j)
# Contrainte 2 :
for i in range(1, N + 1):
    constraints += "\tc_2_{}: ".format(i) + " + ".join("x_{}_{}({})".format(i, j, l_i[i - 1]) for j in range(1, M + 1))
    constraints += " = 1\n"

# Variables de décision :
# m_j :
variables = "".join("\tm_{}\n".format(i) for i in range(1, M + 1))
# x_i_j :
variables += "".join("\tx_{}_{}({})\n".format(i, j, l_i[i - 1]) for i in range(1, N + 1) for j in range(1, M + 1))

# Instance en langage CPLEX LP
CPLEX_instance = "Minimize\n{}Subject To\n{}Binary\n{}End".format(objective, constraints, variables)

print(CPLEX_instance)