#!/usr/bin/env python3

"""
Nom : BAKKALI Yahya
Matricule : 000445166
"""

from sys import argv

f = open(argv[1])
it = 0
M = 0
N = 0
L = 0
l_i = []

for line in f:
    if it == 0:
        value = line.strip().split()
        M = int(value[1])
        L = float(value[0])
        it += 1
    else:
        value = line.strip().split()
        N += int(value[1])
        for i in range(int(value[1])):
            l_i.append((value[0]))

f.close()

output_file = "Minimize\n" \
    "\tobj: " + " + ".join("m_{}".format(i) for i in range(1, M + 1)) + "\n" \
    "Subject To\n "

for j in range(1, M + 1):
    output_file += "\tcontrainte_1_{}: ".format(j) + " + ".join("{} x_{}_{}".format(l_i[i - 1], i, j) for i in range(1, N + 1)) + " <= {}\n".format(L)

for i in range(1, N + 1):
    output_file += "\tcontrainte_2_{}: ".format(i) + " + ".join("x_{}_{}".format(i, j) for j in range(1, M + 1)) + " = 1\n"

output_file += "\tcontrainte_3: " + " + ".join("{} m_{}".format(L,i) for i in range(1, M + 1))

for j in range(1, M + 1):
    output_file += " - "
    output_file += " - ".join("{} x_{}_{}".format(l_i[i - 1], i, j) for i in range(1, N + 1))
output_file += " >= 0\n"

output_file += "Binary\n"

for i in range(1, M + 1):
    output_file += "\tm_{}\n".format(i)

for i in range(1, N + 1):
    for j in range(1, M + 1):
        output_file += "\tx_{}_{}\n".format(i, j)
output_file += "End\n"

print(output_file)

f = open("file.lp", "w")
f.write(output_file)
f.close()
