#!/usr/bin/env python3

"""
Nom : BAKKALI Yahya
Matricule : 000445166
"""
from sys import argv
f = open(argv[1])

# Indices :
M, N = 0, 0
# Constantes :
L, l_i = 0, []

# Lire l'instance et extraire les données.
it = 0
for line in f:
    value = line.strip().split()
    if it == 0:
        M = int(value[1])
        L = value[0]
        it += 1
    else:
        N += int(value[1])
        for i in range(int(value[1])):
            l_i.append((value[0]))

f.close()

# Fonction objective :
objective = "\tobj: " + " + ".join("m_{}".format(i) for i in range(1, M + 1)) + "\n"

# Contraintes :
constraints = ""
# Contrainte 1 :
for j in range(1, M + 1):
    constraints += "\tconstraint_1_{}: ".format(j) + " + ".join("{} x_{}_{}".format(l_i[i - 1], i, j) for i in range(1, N + 1))
    constraints += " <= {}\n".format(L)
# Contrainte 2 :
for i in range(1, N + 1):
    constraints += "\tconstraint_2_{}: ".format(i) + " + ".join("x_{}_{}".format(i, j) for j in range(1, M + 1))
    constraints += " = 1\n"
# Contrainte 3 :
constraints += "\tconstraint_3: " + " + ".join("{} m_{}".format(L, i) for i in range(1, M + 1))
for j in range(1, M + 1):
    constraints += "".join(" - {} x_{}_{}".format(l_i[i - 1], i, j) for i in range(1, N + 1))
constraints += " >= 0\n"

# Variables de décision :
# m_j :
variables = "".join("\tm_{}\n".format(i) for i in range(1, M + 1))
# x_i_j :
variables += "".join("\tx_{}_{}\n".format(i, j) for i in range(1, N + 1) for j in range(1, M + 1))

# Instance en langage CPLEX LP
CPLEX_instance = "Minimize\n{}Subject To\n{}BINARY\n{}END".format(objective, constraints, variables)

f = open("file.lp", "w")
f.write(CPLEX_instance)
f.close()
